apiVersion: v1  # API version for the Service resource.
kind: Service  # Resource type: Service.
metadata:
  name: nginx-service  # Name of the Service.
spec:
  type: NodePort  # Exposes the Service on each Node's IP at a static port.
  selector:
    app: nginx  # Targets pods with the label `app: nginx`.
  ports:
    - protocol: TCP  # Protocol for the Service.
      port: 80  # Port exposed by the Service.
      targetPort: 80  # Port on the container to forward traffic to.
      nodePort: 30000  # Static port on each Node to access the Service.
