apiVersion: autoscaling/v2  # API version for HPA.
kind: HorizontalPodAutoscaler  # HPA resource type.
metadata:
  name: nginx-hpa  # Name of the HPA.
spec:
  scaleTargetRef:  # Target resource to scale.
    apiVersion: apps/v1  # API version of the target.
    kind: Deployment  # Target type (Deployment).
    name: nginx-deployment  # Name of the target Deployment.
  minReplicas: 1  # Minimum number of pods.
  maxReplicas: 10  # Maximum number of pods.
  metrics:  # Metrics used for scaling.
  - type: Resource  # Monitor resource usage.
    resource:
      name: cpu  # Resource type (CPU).
      target:
        type: Utilization  # Target metric is utilization.
        averageUtilization: 2  # Target average CPU utilization (low for demo).
  behavior:  # Defines scaling behavior.
    scaleUp:  # Behavior when scaling up.
      stabilizationWindowSeconds: 0  # No delay for scaling up.
      policies:
      - type: Pods  # Scale by number of pods.
        value: 1  # Add 1 pod per scaling action.
        periodSeconds: 1  # At least 1 seconds between actions.
    scaleDown:  # Behavior when scaling down.
      stabilizationWindowSeconds: 2  # 2-second delay to stabilize before scaling down.
      policies:
      - type: Pods  # Scale by number of pods.
        value: 1  # Remove 1 pod per scaling action.
        periodSeconds: 1  # At least 1 seconds between actions.
